/* 网页后台文案表(中/英)—— 从 `admin.js` 搬出来的那 554 行(公约②边改边拆)。

   为什么搬:巨型文件适用「只许搬出、不许新增」,而 D156 要往顶栏那行加逻辑。
   搬**纯数据**是这两个文件里风险最低的一刀:没有分支、没有闭包、不依赖任何运行时变量。

   用法不变:`admin.js` 里 `const copy = window.AdminCopy`,`t(key)` 照旧。
   加一句文案就在这里加,zh / en 两边都要有 —— 缺哪边 `t()` 就把 key 原样吐到界面上。 */
window.AdminCopy = {
  zh: {
    adminTitle: '有迹 · 商家后台',
    ownerConsole: '店主控制台',
    staffConsole: '员工工作台',
    customerApp: '客户网页',
    reload: '刷新',
    ownerAccess: '后台权限',
    ownerLogin: '后台登录',
    ownerLoginText: '老板用 owner 邮箱登录,看到全部功能。员工请用员工邮箱登录:只会看到订单、排班和图库工作区,不会看到财务与客户档案。',
    email: '邮箱',
    password: '密码',
    login: '登录',
    registerOwner: '注册 Owner',
    logout: '退出',
    bookings: '订单管理',
    dashboard: '后台首页',
    dashboardSubtitle: '当天运营、本月趋势、财务与预约完成度总览',
    monthlyRevenue: '待验证月收入',
    monthServices: '月服务',
    totalServices: '总服务',
    openFinance: '查看财务',
    financeLogin: '财务登录',
    financeText: '总收入和完整财务数据需要二次验证后查看。',
    financePassword: '财务密码',
    totalRevenue: '总收入',
    financeUnlocked: '财务信息已解锁。',
    navBookings: '订单管理',
    navSchedule: '员工管理',
    navStaffPerformance: '技师业绩',
    navServices: '服务管理',
    navCustomers: '客户档案',
    navWechatMock: '客服工作台',
    navAiGallery: 'AI 图库',
    navStoreSettings: '门店设置',
    storeSettingsEyebrow: '商家自助设置',
    storeSettingsTitle: '门店设置',
    storeSettingsSubtitle: '保存后 AI 回答与预约空位立即生效',
    businessHoursTitle: '营业时间',
    businessHoursSaved: '营业时间已保存，AI 回答与预约空位立即生效。',
    closedDay: '休息',
    lastUpdatedLabel: '最近修改',
    needsHumanQueue: '需人工处理',
    takeOverChat: '接管',
    releaseChatToAi: '归还 AI',
    filterAll: '全部',
    filterNeedsHuman: '需人工',
    filterAiActive: 'AI 接待中',
    searchCustomers: '搜索顾客',
    customerProfileCard: '顾客档案',
    aiMemoryCard: 'AI 工作记忆',
    quoteTasksCard: '报价任务',
    backendTasksCard: '后台任务',
    noTasks: '无进行中任务',
    mockPreviewGroup: 'Mock 预演（测试）',
    intentLabel: '意图',
    stageLabel: '阶段',
    refImagesLabel: '参考图',
    knowledgePanelGroup: '知识匹配详情',
    backendWorkflowGroup: '后端流程详情',
    takenOverToast: '已接管，AI 停止自动回复。',
    releasedToAiToast: '已归还 AI 接待。',
    wechatMockEyebrow: '企微 / 微信客服',
    wechatMockTitle: '客服工作台',
    wechatMockSubtitle: '真实会话优先，需人工处理的会话置顶；Mock 预演仅用于测试。',
    wechatSessionTitle: '进线会话',
    mockOnly: 'Mock 预演',
    aiReception: 'AI 接待',
    customerTimeline: '客户对话流',
    staffQuoteWorkbench: '技师报价工作台',
    sourceChannelQuestion: '渠道来源询问',
    quoteTask: '报价任务',
    waitingArtistQuote: '等待技师报价',
    quoteReturned: '技师已回价',
    draftPending: '草稿待确认',
    draftCreated: '预约草稿已创建',
    reminderSent: '10 分钟提醒已发送',
    draftReleased: '30 分钟已释放',
    paidConfirmed: '定金已支付',
    artistReply: '技师回价',
    canDo: '可做',
    cannotDo: '不可做',
    quotePriceCad: '报价 CAD',
    quoteDurationMin: '预计时长分钟',
    quoteNotes: '注意事项 / 缺失元素',
    aiPolishReply: 'AI 润色并回复',
    createDraft: '创建预约草稿',
    sendPaymentReminder: '发送 10 分钟提醒',
    releaseDraft: '释放 30 分钟草稿',
    miniProgramLink: '小程序草稿链接',
    quoteElements: '参考图要素',
    handoffRoute: '人工路由',
    expectedReplyTime: '预计 10 分钟内回价',
    noWechatSession: '暂无会话',
    wechatConnectionStatus: '真实接入状态',
    wechatWebhookUrl: '企业微信回调 URL',
    wechatConfigReady: '凭证已就绪',
    wechatConfigPending: '等待企业微信凭证',
    liveConversations: '真实/测试会话',
    sendMockInbound: '发送模拟微信消息',
    mockCustomerMessage: '客户消息',
    mockSource: '来源',
    injectMock: '注入测试消息',
    customerChatSimulator: '顾客端聊天模拟器',
    customerChatHint: '连续发消息测试 AI 是否按上下文回复；需要人工时右侧后台承接。',
    customerId: '顾客 ID',
    newMockCustomer: '新顾客',
    sendAsCustomer: '顾客发送',
    forceAiReply: '交回 AI 回复',
    adminManualReply: '后台人工承接',
    adminManualReplyHint: '用于模拟转人工、技师报价或复杂情况人工回复。人工回复后，会话会保持人工接管状态。',
    sendManualReply: '发送人工回复',
    sendKeepHuman: '发送并保持人工接管',
    sendReleaseAi: '发送并交回 AI',
    humanHandoffHint: '保持人工后，顾客新消息不会触发 AI；10 分钟无人工回复后会自动交回 AI。',
    waitingHuman: '等待人工',
    aiAutoReplied: 'AI 已回复',
    missingCredentials: '缺少配置',
    configured: '已配置',
    noLiveConversations: '暂无真实或测试会话。你可以先发送一条模拟微信消息。',
    aiDailyBrief: 'AI 今日简报',
    generateBrief: '生成简报',
    aiGallery: 'AI 图库',
    aiGallerySubtitle: '完工作品、AI 文案与可发布素材',
    aiBookingSummary: 'AI 订单摘要',
    aiCustomerInsight: 'AI 客户洞察',
    aiSocialCopy: '生成社媒文案',
    aiProcessing: 'AI 处理中...',
    xiaohongshu: '小红书',
    douyin: '抖音',
    instagram: 'Instagram',
    aiNoWork: '暂无完工作品图，技师上传后会进入图库。',
    copyCaption: '复制文案',
    aiStatusUploaded: '已上传',
    aiStatusProcessing: 'AI 处理中',
    aiStatusReview: '待确认',
    aiStatusReady: '可发布',
    originalImage: '原图',
    editedImage: 'AI 修图版',
    shareLink: '转发链接',
    openShare: '打开分享页',
    viewWork: '查看作品',
    galleryBack: '返回图库',
    confirmGallery: '确认入库',
    selectedImages: '已选图片',
    lockedGallery: '已完成',
    draftGallery: '待确认',
    lockedAt: '确认时间',
    downloadImage: '下载图片',
    uploadMoreImages: '上传更多图片',
    mainImage: '主图',
    platformLinks: '发布平台',
    todayOverview: '今日运营',
    monthOverview: '本月趋势',
    bookingLoad: '预约完成度',
    customerTraffic: '客户流量',
    channelTraffic: '渠道来源',
    retentionReminder: '留存率提醒',
    retentionRate: '留存率',
    revisitDue: '待回访客户',
    dailyRevenueTrend: '月收入趋势',
    dailyDetail: '每日明细',
    popularStyle: '最热门款式',
    topRatedTechnician: '本月完成最多技师',
    estimatedRating: '好评度',
    technicianPerformance: '技师业绩',
    myTechnicianPerformance: '我的技师业绩',
    staffPerformanceHint: '这里只显示当前登录技师的本月人数、服务次数、金额和当前状态。',
    techStatus: '当前状态',
    servingNow: '服务中',
    scheduledToday: '今日有预约',
    available: '可安排',
    monthPeople: '本月人数',
    monthAmount: '本月金额',
    monthCompletedAmount: '本月已完成金额',
    todayBookings: '今日预约',
    activeBookings: '进行中预约',
    totalCustomers: '客户总数',
    recentCustomers: '最近到店',
    dashboardDetails: '数据明细',
    viewDetails: '查看明细',
    noDetailItems: '暂无对应明细',
    financeLockedHint: '点击月收入后输入财务密码，可查看总收入。',
    pendingServices: '待支付服务',
    confirmedServices: '已确认服务',
    monthServiceDetails: '本月已完成服务',
    totalServiceDetails: '全部已完成服务',
    customers: '客户档案',
    customerSortAlpha: '按首字母',
    customerSortVisits: '按到店次数',
    customerSortRecent: '最近到店',
    filter: '筛选',
    visits: '到店次数',
    viewCustomerFile: '查看档案',
    customerRecords: '到店记录',
    backToCustomers: '返回客户列表',
    noCustomerRecords: '暂无到店记录',
    recordImages: '图片记录',
    customerSince: '建档时间',
    lastVisit: '最近到店',
    totalSpent: '累计消费',
    noCustomers: '暂无客户档案',
    bookingsSubtitle: '全部订单数据，状态变化不会隐藏订单',
    sourceChannel: '途径',
    today: '今天',
    allBookings: '全部预约',
    calendar: '日历',
    date: '日期',
    status: '状态',
    clear: '清除',
    schedule: '技师排班',
    technician: '技师',
    start: '开始',
    end: '结束',
    workingDay: '工作日',
    saveSchedule: '保存排班',
    confirmed: '已确认',
    pending: '待支付',
    completed: '已完成',
    cancelled: '已取消',
    expired: '已过期',
    activeAttention: '需关注',
    afterSalesOpen: '售后中',
    afterSalesDone: '售后完成',
    afterSalesWord: '售后',
    afterSalesAttention: '售后处理完成前需要关注。',
    allStatuses: '全部状态',
    services: '服务',
    addService: '添加服务',
    modify: '修改',
    save: '保存',
    cancel: '取消',
    active: '上架',
    hidden: '隐藏',
    serviceEditor: '服务编辑',
    type: '类型',
    category: '分类',
    nameZh: '中文名',
    nameEn: '英文名',
    descriptionZh: '中文描述',
    descriptionEn: '英文描述',
    imageUrl: '服务图片',
    uploadImage: '上传图片',
    priceCad: '价格 CAD',
    depositCad: '定金 CAD',
    depositLabel: '定金',
    durationMin: '时长分钟',
    sortOrder: '排序',
    noBookings: '没有找到预约',
    adjustFilters: '请调整日期或状态筛选。',
    noServices: '暂无服务',
    needsAttention: '定金、排班或服务完成前需要关注。',
    finalDue: '尾款',
    revenue: '收入',
    serviceSaved: '服务已保存。',
    serviceCreated: '服务已添加。',
    scheduleSaved: '排班已保存。',
    loggedOut: '已退出。',
    loginSuccess: '后台登录成功。',
    ownerCreated: 'Owner 账号已创建。',
    checkEmail: '请检查邮箱验证账号，然后再登录。',
    staffMode: '员工模式',
    restrictedForStaff: '员工账号仅显示订单、技师状态与 AI 图库工作流。',
    details: '详情',
    bookingDetails: '订单详情',
    customer: '顾客',
    orderCode: '订单号',
    notes: '备注',
    referenceImages: '参考图',
    workImages: '作品留档',
    uploadWorkImages: '上传完工作品',
    noWorkImages: '暂无完工作品图',
    workImagesSaved: '作品图已保存。',
    noNotes: '暂无备注',
    noImages: '暂无参考图',
    close: '关闭'
  },
  en: {
    adminTitle: 'Youji Merchant Admin',
    ownerConsole: 'Owner Console',
    staffConsole: 'Staff Console',
    customerApp: 'Customer App',
    reload: 'Reload',
    ownerAccess: 'Admin Access',
    ownerLogin: 'Admin Login',
    ownerLoginText: 'Owners see everything. Staff: log in with your staff email — you will only see bookings, schedule and the gallery workspace, never finance or customer files.',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    registerOwner: 'Register Owner',
    logout: 'Log out',
    bookings: 'Orders',
    dashboard: 'Admin Home',
    dashboardSubtitle: 'Today, month, finance, traffic, and completion overview',
    monthlyRevenue: 'Verified Month Revenue',
    monthServices: 'Monthly Services',
    totalServices: 'Total Services',
    openFinance: 'View Finance',
    financeLogin: 'Finance Login',
    financeText: 'Total revenue and full finance data require a second verification.',
    financePassword: 'Finance Password',
    totalRevenue: 'Total Revenue',
    financeUnlocked: 'Finance unlocked.',
    navBookings: 'Order Management',
    navSchedule: 'Staff',
    navStaffPerformance: 'My Performance',
    navServices: 'Services',
    navCustomers: 'Customer Profiles',
    navWechatMock: 'Service Workbench',
    navAiGallery: 'AI Gallery',
    navStoreSettings: 'Store Settings',
    storeSettingsEyebrow: 'Merchant Self-Service',
    storeSettingsTitle: 'Store Settings',
    storeSettingsSubtitle: 'Changes apply instantly to AI answers and booking availability',
    businessHoursTitle: 'Business Hours',
    businessHoursSaved: 'Business hours saved. AI answers and availability updated instantly.',
    closedDay: 'Closed',
    lastUpdatedLabel: 'Last updated',
    needsHumanQueue: 'Needs Human',
    takeOverChat: 'Take Over',
    releaseChatToAi: 'Return to AI',
    filterAll: 'All',
    filterNeedsHuman: 'Needs Human',
    filterAiActive: 'AI Active',
    searchCustomers: 'Search customers',
    customerProfileCard: 'Customer Profile',
    aiMemoryCard: 'AI Working Memory',
    quoteTasksCard: 'Quote Tasks',
    backendTasksCard: 'Backend Tasks',
    noTasks: 'No active tasks',
    mockPreviewGroup: 'Mock Previews (testing)',
    intentLabel: 'Intent',
    stageLabel: 'Stage',
    refImagesLabel: 'Reference images',
    knowledgePanelGroup: 'Knowledge Match Details',
    backendWorkflowGroup: 'Backend Workflow Details',
    takenOverToast: 'Taken over. AI replies paused.',
    releasedToAiToast: 'Returned to AI.',
    wechatMockEyebrow: 'WeCom / WeChat Service',
    wechatMockTitle: 'Customer Service Workbench',
    wechatMockSubtitle: 'Live conversations first; needs-human chats pinned on top. Mock previews are for testing only.',
    wechatSessionTitle: 'Inbound Sessions',
    mockOnly: 'Mock Preview',
    aiReception: 'AI Reception',
    customerTimeline: 'Customer Timeline',
    staffQuoteWorkbench: 'Staff Quote Workbench',
    sourceChannelQuestion: 'Source Channel Question',
    quoteTask: 'Quote Task',
    waitingArtistQuote: 'Waiting for staff quote',
    quoteReturned: 'Quote Returned',
    draftPending: 'Draft Pending',
    draftCreated: 'Booking Draft Created',
    reminderSent: '10-min Reminder Sent',
    draftReleased: '30-min Draft Released',
    paidConfirmed: 'Deposit Paid',
    artistReply: 'Artist Reply',
    canDo: 'Can do',
    cannotDo: 'Cannot do',
    quotePriceCad: 'Quote CAD',
    quoteDurationMin: 'Estimated Duration Min',
    quoteNotes: 'Notes / Missing Elements',
    aiPolishReply: 'AI Polish & Reply',
    createDraft: 'Create Booking Draft',
    sendPaymentReminder: 'Send 10-min Reminder',
    releaseDraft: 'Release 30-min Draft',
    miniProgramLink: 'Mini Program Draft Link',
    quoteElements: 'Reference Elements',
    handoffRoute: 'Handoff Route',
    expectedReplyTime: 'Expected within 10 minutes',
    noWechatSession: 'No sessions',
    wechatConnectionStatus: 'Real Integration Status',
    wechatWebhookUrl: 'WeCom callback URL',
    wechatConfigReady: 'Credentials ready',
    wechatConfigPending: 'Waiting for WeCom credentials',
    liveConversations: 'Live/Test Conversations',
    sendMockInbound: 'Send mock WeChat message',
    mockCustomerMessage: 'Customer message',
    mockSource: 'Source',
    injectMock: 'Inject Test Message',
    customerChatSimulator: 'Customer Chat Simulator',
    customerChatHint: 'Send continuous customer messages to test AI context. When handoff is needed, reply from the admin side.',
    customerId: 'Customer ID',
    newMockCustomer: 'New Customer',
    sendAsCustomer: 'Send as Customer',
    forceAiReply: 'Return to AI',
    adminManualReply: 'Admin Manual Reply',
    adminManualReplyHint: 'Simulate human takeover, technician quotes, or complex replies. After manual reply, this conversation stays in human takeover.',
    sendManualReply: 'Send Manual Reply',
    sendKeepHuman: 'Send and keep human',
    sendReleaseAi: 'Send and return to AI',
    humanHandoffHint: 'When kept human, new customer messages will not trigger AI. AI resumes after 10 minutes without a staff reply.',
    waitingHuman: 'Waiting for human',
    aiAutoReplied: 'AI replied',
    missingCredentials: 'Missing config',
    configured: 'Configured',
    noLiveConversations: 'No live or test conversations yet. Send a mock WeChat message first.',
    aiDailyBrief: 'AI Daily Brief',
    generateBrief: 'Generate Brief',
    aiGallery: 'AI Gallery',
    aiGallerySubtitle: 'Finished work, AI captions, and publish-ready assets',
    aiBookingSummary: 'AI Booking Summary',
    aiCustomerInsight: 'AI Customer Insight',
    aiSocialCopy: 'Generate Social Copy',
    aiProcessing: 'AI working...',
    xiaohongshu: 'RED',
    douyin: 'Douyin',
    instagram: 'Instagram',
    aiNoWork: 'No finished work yet. Uploaded work photos will appear here.',
    copyCaption: 'Copy Caption',
    aiStatusUploaded: 'Uploaded',
    aiStatusProcessing: 'AI Processing',
    aiStatusReview: 'Needs Review',
    aiStatusReady: 'Publish Ready',
    originalImage: 'Original',
    editedImage: 'AI Edited',
    shareLink: 'Share Link',
    openShare: 'Open Share Page',
    viewWork: 'View Work',
    galleryBack: 'Back to Gallery',
    confirmGallery: 'Approve to Portfolio',
    selectedImages: 'Selected Images',
    lockedGallery: 'Completed',
    draftGallery: 'Needs Review',
    lockedAt: 'Approved At',
    downloadImage: 'Download Image',
    uploadMoreImages: 'Upload More Images',
    mainImage: 'Main Image',
    platformLinks: 'Publish Platforms',
    todayOverview: 'Today Overview',
    monthOverview: 'Month Trend',
    bookingLoad: 'Booking Completion',
    customerTraffic: 'Customer Traffic',
    channelTraffic: 'Channel Sources',
    retentionReminder: 'Retention Reminder',
    retentionRate: 'Retention Rate',
    revisitDue: 'Revisit Due',
    dailyRevenueTrend: 'Revenue Trend',
    dailyDetail: 'Daily Detail',
    popularStyle: 'Most Popular Style',
    topRatedTechnician: 'Top Technician (completed)',
    estimatedRating: 'Rating',
    technicianPerformance: 'Technician Performance',
    myTechnicianPerformance: 'My Technician Performance',
    staffPerformanceHint: 'Only your own monthly guests, services, revenue, and current status are shown here.',
    techStatus: 'Current Status',
    servingNow: 'Serving',
    scheduledToday: 'Booked Today',
    available: 'Available',
    monthPeople: 'Month Guests',
    monthAmount: 'Month Amount',
    monthCompletedAmount: 'Completed Amount',
    todayBookings: 'Today Bookings',
    activeBookings: 'Active Bookings',
    totalCustomers: 'Total Customers',
    recentCustomers: 'Recent Visits',
    dashboardDetails: 'Data Details',
    viewDetails: 'View Details',
    noDetailItems: 'No matching details',
    financeLockedHint: 'Open monthly revenue and enter the finance password to view total revenue.',
    pendingServices: 'Pending Payment Services',
    confirmedServices: 'Confirmed Services',
    monthServiceDetails: 'Completed This Month',
    totalServiceDetails: 'All Completed Services',
    customers: 'Customer Profiles',
    customerSortAlpha: 'A-Z',
    customerSortVisits: 'Visits',
    customerSortRecent: 'Recent Visit',
    filter: 'Filter',
    visits: 'Visits',
    viewCustomerFile: 'Open Profile',
    customerRecords: 'Visit Records',
    backToCustomers: 'Back to Customers',
    noCustomerRecords: 'No visit records yet',
    recordImages: 'Image Records',
    customerSince: 'Profile Since',
    lastVisit: 'Last Visit',
    totalSpent: 'Total Spent',
    noCustomers: 'No customer profiles',
    bookingsSubtitle: 'All orders stay visible when status changes',
    sourceChannel: 'Source Channel',
    today: 'Today',
    allBookings: 'All Bookings',
    calendar: 'Calendar',
    date: 'Date',
    status: 'Status',
    clear: 'Clear',
    schedule: 'Technician Schedule',
    technician: 'Technician',
    start: 'Start',
    end: 'End',
    workingDay: 'Working day',
    saveSchedule: 'Save Schedule',
    confirmed: 'Confirmed',
    pending: 'Pending',
    completed: 'Completed',
    cancelled: 'Cancelled',
    expired: 'Expired',
    activeAttention: 'Active attention',
    afterSalesOpen: 'After-sales open',
    afterSalesDone: 'After-sales resolved',
    afterSalesWord: 'After-sales',
    afterSalesAttention: 'Needs attention until after-sales is resolved.',
    allStatuses: 'All statuses',
    services: 'Services',
    addService: 'Add Service',
    modify: 'Modify',
    save: 'Save',
    cancel: 'Cancel',
    active: 'Active',
    hidden: 'Hidden',
    serviceEditor: 'Service Editor',
    type: 'Type',
    category: 'Category',
    nameZh: 'Chinese Name',
    nameEn: 'English Name',
    descriptionZh: 'Chinese Description',
    descriptionEn: 'English Description',
    imageUrl: 'Service Image',
    uploadImage: 'Upload Image',
    priceCad: 'Price CAD',
    depositCad: 'Deposit CAD',
    depositLabel: 'Deposit',
    durationMin: 'Duration min',
    sortOrder: 'Sort order',
    noBookings: 'No bookings found',
    adjustFilters: 'Adjust the date or status filter.',
    noServices: 'No services yet',
    needsAttention: 'Needs attention until deposit, schedule, or completion is settled.',
    finalDue: 'Final due',
    revenue: 'Revenue',
    serviceSaved: 'Service saved.',
    serviceCreated: 'Service created.',
    scheduleSaved: 'Schedule saved.',
    loggedOut: 'Logged out.',
    loginSuccess: 'Admin login successful.',
    ownerCreated: 'Owner account created.',
    checkEmail: 'Check your email to confirm the account, then log in.',
    staffMode: 'Staff Mode',
    restrictedForStaff: 'Staff accounts only show orders, technician status, and AI gallery workflow.',
    details: 'Details',
    bookingDetails: 'Booking Details',
    customer: 'Customer',
    orderCode: 'Order Code',
    notes: 'Notes',
    referenceImages: 'Reference Images',
    workImages: 'Work Archive',
    uploadWorkImages: 'Upload Finished Work',
    noWorkImages: 'No finished work photos',
    workImagesSaved: 'Work photos saved.',
    noNotes: 'No notes',
    noImages: 'No reference images',
    close: 'Close'
  }
}
