/* 顾客端中英文案表 —— 从 `customer.js` 整块摘出来(裁 #105,夜13 §六)。
 *
 * 为什么摘:`customer.js` 2,755 行**正好压在棘轮上**,下一次任何改动都会顶破。
 * 裁 #89 说顶破只有三个正确反应:**摘出去 / 请裁 / 说明非加不可** —— 压行不在里面。
 * 裁 #105 又补了一条:**摘出去要跟着降棘轮,不许留余量** —— 所以摘完当批把棘轮降到实测值。
 *
 * ⚠️ 这一份要在 `customer.js` **之前**加载;`customer-auth-copy.js` 又要在这一份之前
 * (裁 #103 那两条款文从那边合并进来)。
 * `customer.js` 那头取不到时有内置兜底 —— 判据 ㉜「顶层加载不炸」当场咬过一次,
 * 就是 `customer-auth-copy` 那回:顶层直接展开一个还没加载的全局,整页白屏。
 */
/* 🔴 **工厂式,不是纯数据** —— 现测这张表里有 `${moneyY(50)}` 这种**对外部函数的调用**
 * (`moneyY` 住在 `customer.js`)。整块当纯数据摘出去,加载那一刻就 `ReferenceError`,**整页白屏**。
 * 这一条是摘的时候当场量出来的(`node -e` 直接 require 这份文件,它自己报的错),
 * **不是看出来的** —— 所以摘出去的东西要先跑一次,别只看行数对不对。
 * 改成工厂:`customer.js` 在 `moneyY` 定义好之后调它一次。 */
window.CustomerCopyFactory = ({ moneyY }) => ({
  zh: {
    /* 裁 #103:这两条与它的全部理由在 ./customer-auth-copy.js(摘出去,裁#89)。
       ⚠️ 取不到就用内置兜底 —— 判据 ㉜「顶层加载不炸」当场咬过一次:
       直接 `...window.CustomerAuthCopy.zh` 会在那个文件没先加载时炸掉整页。
       **一个只在加载顺序对的时候才不炸的页面,换个人改 html 就炸给顾客看。** */
    ...((window.CustomerAuthCopy || {}).zh || { registerTitle: '用微信登录', registerText: '在店里消费过?用微信扫一下下面的码。' }),
    emailLogin: '邮箱登录',
    displayName: '姓名',
    email: '邮箱',
    password: '密码',
    googleRegister: '使用 Google 登录',
    guideTitle: '在微信里打开',
    guideText: '顾客端的下单、卡包、订单在小程序里,扫下面的小程序码就能进。店铺、作品、价目在这里照常可以看。',
    guideNoQr: '本店还没有配小程序码 —— 在微信里搜索店名也能找到。',
    continueGuest: '继续游客浏览',
    enter: '进入',
    home: '首页',
    services: '服务',
    cart: '购物车',
    me: '我的',
    bookNow: '立即预约',
    viewStore: '查看门店',
    quickNail: '美甲服务',
    quickLash: '美睫服务',
    quickMember: '会员档案',
    technicianWorks: '技师作品',
    technicianPortfolio: '技师作品集',
    portfolioIntro: '浏览每位技师已确认入库的真实作品。',
    noPortfolio: '暂无已确认作品，作品确认后会自动出现在这里。',
    viewWork: '查看作品',
    popularNail: '人气美甲',
    popularLash: '人气美睫',
    nail: '美甲 Nail',
    lash: '美睫 Lash',
    minutes: '分钟',
    deposit: '定金',
    servicePrice: '服务价',
    basePrice: '基础价',
    fixedPrice: '固定价',
    detailedQuote: '详细价格请联系客服获取报价',
    finalPriceGuide: '加项确认后即为最终报价',
    priceBoundary: '价格说明',
    aiPriceSuggestion: 'AI 价格建议',
    manualQuote: '联系人工报价',
    process: '服务流程',
    notice: '注意事项',
    reference: '参考图',
    addToCart: '加入购物车',
    appointment: '预约时间',
    artist: '服务技师',
    date: '到店日期',
    addOns: '附加服务',
    optional: '可选',
    remark: '备注',
    upload: '上传参考图',
    aiAnalyze: 'AI 分析参考图',
    aiAnalyzing: 'AI 正在分析...',
    aiReferenceTitle: 'AI 款式建议',
    aiMockBadge: '演示分析',
    aiMockNotice: '当前是 mock 价格建议，仅用于流程测试；复杂款式和最终报价仍需人工确认。',
    aiComplexity: '复杂度',
    aiExtraTime: '建议额外时间',
    aiTechNote: '给技师的备注',
    checkout: '去结算',
    saveCart: '保存到购物车',
    requiredDeposit: '需付定金',
    emptyCart: '购物车是空的',
    emptyCartHint: '请选择服务并填写预约信息。',
    chooseService: '选择服务',
    pendingCheckout: '待结算',
    selectedDeposit: '已选定金',
    confirmOrder: '确认订单',
    mockPay: 'Stripe 测试支付 / Mock 备用',
    discount: '优惠与储值',
    coupon: '新人券',
    balance: '储值余额',
    store: '门店',
    payAction: '支付定金',
    paid: '已确认',
    pending: '待支付',
    memberGrowth: '会员成长值',
    memberBenefits: '会员权益',
    viewMemberBenefits: '查看会员权益',
    memberBenefitsIntro: '查看不同会员等级的升级门槛、定金规则与可享权益。',
    lifetimeSpend: '累计消费',
    depositRule: '定金规则',
    depositWaived: '预约免定金',
    depositRequired: `预约需支付 ${moneyY(50)} 定金`,
    upgradeGift: '升级礼包',
    currentTier: '当前等级',
    memberCode: '会员码',
    staffScan: '店员扫码',
    referralLink: '分享推荐链接',
    copyMemberLink: '复制推荐链接',
    memberCodeCopied: '推荐链接已复制',
    memberCodeHint: '店员扫码可用于识别客户；分享链接可用于后续推荐返佣追踪。',
    points: '积分',
    orders: '我的订单',
    recent: '近期消费',
    functions: '常用功能',
    pointsMall: '积分商城',
    completed: '已完成',
    cancelled: '已取消',
    afterSales: '售后',
    all: '全部',
    orderNo: '订单号',
    bookingInfo: '预约信息',
    payment: '支付信息',
    workArchive: '服务留档',
    finalPhotos: '完工作品',
    noWorkImages: '服务完成后会在这里看到作品照片。',
    downloadImage: '下载图片',
    oneClickShare: '一键分享',
    shareReady: '分享文案与链接',
    shareTo: '分享平台',
    shareLink: '分享链接',
    copyCaption: '复制文案',
    openPlatform: '打开平台',
    captionCopied: '文案已复制',
    arrival: '到店时间',
    duration: '服务时长',
    technician: '服务人员',
    address: '地址',
    none: '无',
    paidDeposit: '实付定金',
    finalDue: '到店尾款',
    totalSpent: '累计消费',
    visits: '到店次数',
    times: '次',
    back: '返回',
    logout: '退出登录',
    completeFlow: '完整预约流程',
    noSlots: '当天暂无可预约时间',
    created: '已加入购物车',
    /* 🔴 10f「平台记账,不代收」:平台没收到钱,顾客端就不能替钱说话。
       「已支付」的意思是「平台收到了」——而平台没有。说的只能是门店确认了。 */
    paidDone: '门店已确认收到定金，预约已确认',
    needLogin: '请先登录后继续',   // 裁#103:不许出现「注册」
    confirmEmail: '请检查邮箱完成验证，然后再登录。',
    paymentRedirect: '正在跳转到 Stripe 测试支付...',
    sessionExpired: '登录已过期，请重新登录后继续支付。',
    draftLoaded: '已载入预约草稿，请确认后支付定金。',
    draftUnavailable: '预约草稿暂不可用',
    depositPolicyTitle: '定金退改规则',
    depositPolicyText: '预约定金用于锁定技师时间。到店前 24 小时以上取消或改期，定金可退或可转；24 小时内取消或临时改期，定金会扣除一半；临时爽约定金不退。',
    aiAssistant: 'AI 客服',
    aiAssistantIntro: '我可以回答预约、价格、定金、取消改期和订单相关问题。',
    aiAssistantPlaceholder: '输入你的问题...',
    aiSend: '发送',
    aiHandoff: '建议转人工',
    aiHandoffHint: '这个问题需要人工确认，我可以先帮你整理要问的信息。',
    aiQuickPrice: '美甲复杂款怎么报价？',
    aiQuickBooking: '怎么预约？',
    aiQuickPolicy: '取消改期规则？'
  },
  en: {
    ...((window.CustomerAuthCopy || {}).en || { registerTitle: 'Sign in with WeChat', registerText: 'Been to the salon? Scan the code below with WeChat.' }),
    emailLogin: 'Email Login',
    displayName: 'Name',
    email: 'Email',
    password: 'Password',
    googleRegister: 'Continue with Google',
    guideTitle: 'Open in WeChat',
    guideText: 'Booking, cards and orders live in the Mini Program. Scan the code below to enter. Store, works and pricing stay viewable here.',
    guideNoQr: 'This store has no Mini Program code yet — search the store name in WeChat.',
    continueGuest: 'Continue as Guest',
    enter: 'Enter',
    home: 'Home',
    services: 'Services',
    cart: 'Cart',
    me: 'Me',
    bookNow: 'Book Now',
    viewStore: 'View Store',
    quickNail: 'Nail Services',
    quickLash: 'Lash Services',
    quickMember: 'Member Profile',
    technicianWorks: 'Artist Work',
    technicianPortfolio: 'Artist Portfolio',
    portfolioIntro: 'Browse approved finished work by each artist.',
    noPortfolio: 'No approved work yet. Approved photos will appear here automatically.',
    viewWork: 'View Work',
    popularNail: 'Popular Nail',
    popularLash: 'Popular Lash',
    nail: 'Nail',
    lash: 'Lash',
    minutes: 'min',
    deposit: 'Deposit',
    servicePrice: 'Service price',
    basePrice: 'Base price',
    fixedPrice: 'Fixed price',
    detailedQuote: 'Contact us for a detailed quote',
    finalPriceGuide: 'Confirmed add-ons make the final quote',
    priceBoundary: 'Pricing Guide',
    aiPriceSuggestion: 'AI Price Suggestion',
    manualQuote: 'Contact staff for quote',
    process: 'Service Process',
    notice: 'Notice',
    reference: 'Reference',
    addToCart: 'Add to Cart',
    appointment: 'Appointment',
    artist: 'Artist',
    date: 'Date',
    addOns: 'Add-ons',
    optional: 'Optional',
    remark: 'Notes',
    upload: 'Upload Reference',
    aiAnalyze: 'AI Analyze Reference',
    aiAnalyzing: 'AI is analyzing...',
    aiReferenceTitle: 'AI Style Suggestion',
    aiMockBadge: 'Demo Analysis',
    aiMockNotice: 'This is a mock pricing suggestion for flow testing only. Complex designs and final quotes still require staff confirmation.',
    aiComplexity: 'Complexity',
    aiExtraTime: 'Suggested extra time',
    aiTechNote: 'Note for technician',
    checkout: 'Checkout',
    saveCart: 'Save to Cart',
    requiredDeposit: 'Deposit due',
    emptyCart: 'Your cart is empty',
    emptyCartHint: 'Choose a service and fill in appointment details.',
    chooseService: 'Choose Service',
    pendingCheckout: 'Pending checkout',
    selectedDeposit: 'Selected deposit',
    confirmOrder: 'Confirm Order',
    mockPay: 'Stripe test payment / mock fallback',
    discount: 'Discount & Balance',
    coupon: 'New member coupon',
    balance: 'Stored balance',
    store: 'Store',
    payAction: 'Pay Deposit',
    paid: 'Confirmed',
    pending: 'Pending payment',
    memberGrowth: 'Member growth',
    memberBenefits: 'Member Benefits',
    viewMemberBenefits: 'View Benefits',
    memberBenefitsIntro: 'See tier thresholds, booking deposit rules, and member perks.',
    lifetimeSpend: 'Lifetime spend',
    depositRule: 'Deposit rule',
    depositWaived: 'Deposit waived',
    depositRequired: `${moneyY(50)} booking deposit required`,
    upgradeGift: 'Upgrade gift',
    currentTier: 'Current tier',
    memberCode: 'Member Code',
    staffScan: 'Staff Scan',
    referralLink: 'Referral Link',
    copyMemberLink: 'Copy Referral Link',
    memberCodeCopied: 'Referral link copied',
    memberCodeHint: 'Staff can scan this to identify the client; the referral link can track future rewards.',
    points: 'Points',
    orders: 'My Orders',
    recent: 'Recent Records',
    functions: 'Common Tools',
    pointsMall: 'Points Mall',
    completed: 'Completed',
    cancelled: 'Cancelled',
    afterSales: 'After-sales',
    all: 'All',
    orderNo: 'Order No.',
    bookingInfo: 'Booking Info',
    payment: 'Payment',
    workArchive: 'Service Archive',
    finalPhotos: 'Finished Work',
    noWorkImages: 'Finished photos will appear here after the service.',
    downloadImage: 'Download',
    oneClickShare: 'Share',
    shareReady: 'Share copy and links',
    shareTo: 'Platform',
    shareLink: 'Share link',
    copyCaption: 'Copy caption',
    openPlatform: 'Open platform',
    captionCopied: 'Caption copied',
    arrival: 'Arrival',
    duration: 'Duration',
    technician: 'Technician',
    address: 'Address',
    none: 'None',
    paidDeposit: 'Paid Deposit',
    finalDue: 'Final Due',
    totalSpent: 'Total Spent',
    visits: 'Visits',
    times: 'times',
    back: 'Back',
    logout: 'Log out',
    completeFlow: 'Full booking flow',
    noSlots: 'No available times',
    created: 'Added to cart',
    paidDone: 'The store has confirmed your deposit. Booking confirmed.',
    needLogin: 'Please sign in to continue',   // 裁#103
    confirmEmail: 'Please verify your email, then sign in.',
    paymentRedirect: 'Redirecting to Stripe test payment...',
    sessionExpired: 'Your session expired. Please sign in again to continue payment.',
    draftLoaded: 'Booking draft loaded. Please confirm and pay the deposit.',
    draftUnavailable: 'Booking draft is unavailable.',
    depositPolicyTitle: 'Deposit Cancellation Policy',
    depositPolicyText: 'The deposit holds your technician time. Cancellations or rescheduling more than 24 hours before the appointment can be refunded or transferred. Within 24 hours, half of the deposit is kept. No-shows are non-refundable.',
    aiAssistant: 'AI Concierge',
    aiAssistantIntro: 'I can help with booking, pricing, deposits, cancellation policy, and order questions.',
    aiAssistantPlaceholder: 'Type your question...',
    aiSend: 'Send',
    aiHandoff: 'Staff recommended',
    aiHandoffHint: 'This needs staff confirmation. I can help organize the question first.',
    aiQuickPrice: 'How are custom nails quoted?',
    aiQuickBooking: 'How do I book?',
    aiQuickPolicy: 'Cancellation policy?'
  }
})
